// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRlkcchEsAH6_BXr0-wZPl5L7b51eDMjo',
    appId: '1:240341093654:web:457a2f57369b75c91c1437',
    messagingSenderId: '240341093654',
    projectId: 'fuely-f1e59',
    authDomain: 'fuely-f1e59.firebaseapp.com',
    storageBucket: 'fuely-f1e59.firebasestorage.app',
    measurementId: 'G-G4E14MYYS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU0-iV-or7JmAfFs_I2doqa8FKw3J_WuA',
    appId: '1:240341093654:android:967d3bb7cc97f23c1c1437',
    messagingSenderId: '240341093654',
    projectId: 'fuely-f1e59',
    storageBucket: 'fuely-f1e59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeZjhN0OZMTwcECBIcbR6hhd4d0fHpAE',
    appId: '1:240341093654:ios:c851b519340cdaec1c1437',
    messagingSenderId: '240341093654',
    projectId: 'fuely-f1e59',
    storageBucket: 'fuely-f1e59.firebasestorage.app',
    iosClientId: '240341093654-sg073n2nhd0np3687n2lf56ehdr92edb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripTankFuely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGeZjhN0OZMTwcECBIcbR6hhd4d0fHpAE',
    appId: '1:240341093654:ios:c851b519340cdaec1c1437',
    messagingSenderId: '240341093654',
    projectId: 'fuely-f1e59',
    storageBucket: 'fuely-f1e59.firebasestorage.app',
    iosClientId: '240341093654-sg073n2nhd0np3687n2lf56ehdr92edb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripTankFuely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRlkcchEsAH6_BXr0-wZPl5L7b51eDMjo',
    appId: '1:240341093654:web:182bdde2085dcea11c1437',
    messagingSenderId: '240341093654',
    projectId: 'fuely-f1e59',
    authDomain: 'fuely-f1e59.firebaseapp.com',
    storageBucket: 'fuely-f1e59.firebasestorage.app',
    measurementId: 'G-FNX13F8570',
  );

}